# Plots Backend Service
apiVersion: v1
kind: Service
metadata:
  name: vision-api
spec:
  type: NodePort
  ports: 
  - port: 80
    nodePort: 32011
    targetPort: 3000
  selector:
    app: vision-api
---
