# Plots Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-api
  labels: 
    app: vision-api
spec:
  selector:
    matchLabels:
      app: vision-api
  replicas: 1
  template: 
    metadata:
      labels:
        app: vision-api
    spec:
      containers:
      - name: vision-api
        image: labshare/vision-api:0.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: vision-api
        env:
        - name: COLLECTION_PATH
          value: "/data/wipp/csv-collections/<id>"
        - name: DATASET_BASE_PATH
          value: "/data/csv/"
        - name: ELASTIC_APM_SERVICE_NAME
          value: vision-api
        volumeMounts:
        - name: shared-data
          mountPath: /data/wipp
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: "wipp-pv-claim"
---
