# Plots Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-ui
  labels: 
    app: vision-ui
spec:
  selector:
    matchLabels:
      app: vision-ui
  replicas: 1
  template: 
    metadata:
      labels:
        app: vision-ui
    spec:
      containers:
      - name: vision-ui
        image: labshare/vision-ui:0.2.17
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: nginx
        env:
        - name: VISION_API_URL
          value: "http://localhost:32011/"
---
