# WIPP Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: wipp-frontend
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    nodePort: 32001
    protocol: TCP
    targetPort: 80
  selector:
    app: wipp-frontend
---
