apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  type: NodePort
  externalIPs:
  - 10.0.2.15
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30201
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
