apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: wipp-frontend
  name: wipp-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: wipp-frontend
    spec:
      containers:
      - image: vm-itl-ssd-201.nist.gov:5000/wipp_dev/wipp_frontend:latest
        name: wipp-frontend
        args: ["wipp-backend", "8080"]
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
status: {}
