apiVersion: v1
kind: ServiceAccount
metadata:
  name: wipp-backend-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wipp-backend-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wipp-backend-rb
subjects:
  - kind: ServiceAccount
    name: wipp-backend-sa
roleRef:
  kind: Role
  name: wipp-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: wipp-backend
  name: wipp-backend
spec:
  selector:
    matchLabels:
      app: wipp-backend
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wipp-backend
    spec:
      serviceAccountName: wipp-backend-sa
      securityContext:
        runAsUser: RUN_AS_USER_VALUE
        runAsGroup: RUN_AS_GROUP_VALUE
      containers:
      - image: WIPP_BACKEND_IMAGE
        name: wipp-backend
        env:
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: KUBE_WIPPDATA_PVC
              value: wippdata-pvc
            - name: KEYCLOAK_AUTHSERVERURL
              value: KEYCLOAK_AUTH_URL_VALUE
            - name: KEYCLOAK_SSLREQUIRED
              value: KEYCLOAK_SSL_REQUIRED_VALUE
            - name: KEYCLOAK_DISABLETRUSTMANAGER
              value: KEYCLOAK_DISABLE_TRUST_MANAGER_VALUE
            - name: OME_CONVERTER_THREADS
              value: OME_CONVERTER_THREADS_VALUE
            - name: ELASTIC_APM_SERVER_URLS
              value: ELASTIC_APM_SERVER_URLS_VALUE
            - name: ELASTIC_APM_SERVICE_NAME
              value: wipp-backend-prod
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: gov.nist.itl.ssd.wipp.backend
            - name: RUN_WORKFLOWS_AS_USER
              value: "RUN_AS_USER_VALUE"
            - name: RUN_WORKFLOWS_AS_GROUP
              value: "RUN_AS_GROUP_VALUE"
        volumeMounts:
        - mountPath: /data/WIPP-plugins
          name: data
        ports:
        - containerPort: 8080
        resources: {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: wippdata-pvc
      restartPolicy: Always
status: {}
