apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:3.6
        name: mongodb
        volumeMounts:
        - mountPath: /data/db
          name: dbdata
        ports:
        - containerPort: 27017
        resources: {}
      volumes:
      - name: dbdata
        hostPath:
          path: /data/WIPP-mongo
          type: Directory
      restartPolicy: Always
status: {}
